import { google } from 'googleapis';
import { oauth2Client } from './client';
import logger from '../../utils/logger';
import { Readable } from 'stream';

/**
 * Google Drive Service - Production-Ready
 * Upload invoices, receipts, and backups to Google Drive
 */

export interface UploadOptions {
  filename: string;
  content: Buffer;
  mimeType: string;
  folderId?: string;
  description?: string;
}

/**
 * Upload file to Google Drive
 */
export async function uploadToDrive(options: UploadOptions): Promise<{ fileId: string; webViewLink: string }> {
  if (!oauth2Client) {
    throw new Error('Google OAuth2 not configured');
  }

  const drive = google.drive({ version: 'v3', auth: oauth2Client });

  try {
    const fileMetadata: any = {
      name: options.filename,
      description: options.description,
    };

    if (options.folderId) {
      fileMetadata.parents = [options.folderId];
    }

    const media = {
      mimeType: options.mimeType,
      body: Readable.from(options.content),
    };

    const response = await drive.files.create({
      requestBody: fileMetadata,
      media,
      fields: 'id, name, webViewLink, webContentLink',
    });

    logger.info('File uploaded to Google Drive', {
      fileId: response.data.id,
      filename: options.filename,
      size: options.content.length,
    });

    return {
      fileId: response.data.id!,
      webViewLink: response.data.webViewLink!,
    };
  } catch (error: any) {
    logger.error('Google Drive upload error:', error);
    throw new Error(`Failed to upload to Google Drive: ${error.message}`);
  }
}

/**
 * Create folder in Google Drive
 */
export async function createFolder(name: string, parentFolderId?: string): Promise<string> {
  if (!oauth2Client) {
    throw new Error('Google OAuth2 not configured');
  }

  const drive = google.drive({ version: 'v3', auth: oauth2Client });

  try {
    const fileMetadata: any = {
      name,
      mimeType: 'application/vnd.google-apps.folder',
    };

    if (parentFolderId) {
      fileMetadata.parents = [parentFolderId];
    }

    const response = await drive.files.create({
      requestBody: fileMetadata,
      fields: 'id',
    });

    logger.info('Folder created in Google Drive', {
      folderId: response.data.id,
      name,
    });

    return response.data.id!;
  } catch (error: any) {
    logger.error('Google Drive folder creation error:', error);
    throw new Error(`Failed to create folder: ${error.message}`);
  }
}

/**
 * Upload invoice PDF to Drive
 */
export async function uploadInvoiceToDrive(
  invoiceNumber: string,
  pdfData: Buffer,
  folderId?: string
): Promise<{ fileId: string; webViewLink: string }> {
  return uploadToDrive({
    filename: `Invoice-${invoiceNumber}.pdf`,
    content: pdfData,
    mimeType: 'application/pdf',
    folderId,
    description: `Invoice ${invoiceNumber} - Generated by AutoInvoice`,
  });
}

/**
 * Upload receipt image to Drive
 */
export async function uploadReceiptToDrive(
  receiptId: string,
  imageData: Buffer,
  vendor: string,
  folderId?: string
): Promise<{ fileId: string; webViewLink: string }> {
  const timestamp = new Date().toISOString().split('T')[0];

  return uploadToDrive({
    filename: `Receipt-${vendor}-${timestamp}.jpg`,
    content: imageData,
    mimeType: 'image/jpeg',
    folderId,
    description: `Receipt from ${vendor} - ID: ${receiptId}`,
  });
}

/**
 * Create backup of database data
 */
export async function uploadDatabaseBackup(
  backupData: string,
  folderId?: string
): Promise<{ fileId: string; webViewLink: string }> {
  const timestamp = new Date().toISOString().replace(/:/g, '-').split('.')[0];

  return uploadToDrive({
    filename: `backup-${timestamp}.json`,
    content: Buffer.from(backupData, 'utf-8'),
    mimeType: 'application/json',
    folderId,
    description: 'AutoInvoice database backup',
  });
}

/**
 * List files in a folder
 */
export async function listFiles(folderId?: string): Promise<any[]> {
  if (!oauth2Client) {
    throw new Error('Google OAuth2 not configured');
  }

  const drive = google.drive({ version: 'v3', auth: oauth2Client });

  try {
    const query = folderId ? `'${folderId}' in parents` : undefined;

    const response = await drive.files.list({
      q: query,
      fields: 'files(id, name, mimeType, createdTime, modifiedTime, size, webViewLink)',
      orderBy: 'modifiedTime desc',
      pageSize: 100,
    });

    return response.data.files || [];
  } catch (error: any) {
    logger.error('Google Drive list error:', error);
    throw new Error(`Failed to list files: ${error.message}`);
  }
}

/**
 * Delete file from Drive
 */
export async function deleteFile(fileId: string): Promise<void> {
  if (!oauth2Client) {
    throw new Error('Google OAuth2 not configured');
  }

  const drive = google.drive({ version: 'v3', auth: oauth2Client });

  try {
    await drive.files.delete({
      fileId,
    });

    logger.info('File deleted from Google Drive', { fileId });
  } catch (error: any) {
    logger.error('Google Drive delete error:', error);
    throw new Error(`Failed to delete file: ${error.message}`);
  }
}

/**
 * Download file from Drive
 */
export async function downloadFile(fileId: string): Promise<Buffer> {
  if (!oauth2Client) {
    throw new Error('Google OAuth2 not configured');
  }

  const drive = google.drive({ version: 'v3', auth: oauth2Client });

  try {
    const response = await drive.files.get(
      {
        fileId,
        alt: 'media',
      },
      { responseType: 'arraybuffer' }
    );

    return Buffer.from(response.data as ArrayBuffer);
  } catch (error: any) {
    logger.error('Google Drive download error:', error);
    throw new Error(`Failed to download file: ${error.message}`);
  }
}

/**
 * Share file with email address
 */
export async function shareFile(fileId: string, email: string, role: 'reader' | 'writer' | 'commenter' = 'reader'): Promise<void> {
  if (!oauth2Client) {
    throw new Error('Google OAuth2 not configured');
  }

  const drive = google.drive({ version: 'v3', auth: oauth2Client });

  try {
    await drive.permissions.create({
      fileId,
      requestBody: {
        type: 'user',
        role,
        emailAddress: email,
      },
      sendNotificationEmail: true,
    });

    logger.info('File shared via Google Drive', { fileId, email, role });
  } catch (error: any) {
    logger.error('Google Drive share error:', error);
    throw new Error(`Failed to share file: ${error.message}`);
  }
}

/**
 * Get or create AutoInvoice folder structure
 */
export async function getOrCreateFolderStructure(): Promise<{
  rootFolder: string;
  invoicesFolder: string;
  receiptsFolder: string;
  backupsFolder: string;
}> {
  // Check if AutoInvoice folder exists
  const drive = google.drive({ version: 'v3', auth: oauth2Client });

  try {
    const searchResponse = await drive.files.list({
      q: "name='AutoInvoice' and mimeType='application/vnd.google-apps.folder' and trashed=false",
      fields: 'files(id, name)',
      pageSize: 1,
    });

    let rootFolder: string;

    if (searchResponse.data.files && searchResponse.data.files.length > 0) {
      rootFolder = searchResponse.data.files[0].id!;
      logger.info('Found existing AutoInvoice folder', { folderId: rootFolder });
    } else {
      rootFolder = await createFolder('AutoInvoice');
      logger.info('Created AutoInvoice root folder', { folderId: rootFolder });
    }

    // Create subfolders
    const [invoicesFolder, receiptsFolder, backupsFolder] = await Promise.all([
      createOrGetSubfolder('Invoices', rootFolder),
      createOrGetSubfolder('Receipts', rootFolder),
      createOrGetSubfolder('Backups', rootFolder),
    ]);

    return {
      rootFolder,
      invoicesFolder,
      receiptsFolder,
      backupsFolder,
    };
  } catch (error: any) {
    logger.error('Folder structure creation error:', error);
    throw new Error(`Failed to create folder structure: ${error.message}`);
  }
}

/**
 * Helper to create or get subfolder
 */
async function createOrGetSubfolder(name: string, parentId: string): Promise<string> {
  const drive = google.drive({ version: 'v3', auth: oauth2Client });

  const searchResponse = await drive.files.list({
    q: `name='${name}' and '${parentId}' in parents and mimeType='application/vnd.google-apps.folder' and trashed=false`,
    fields: 'files(id)',
    pageSize: 1,
  });

  if (searchResponse.data.files && searchResponse.data.files.length > 0) {
    return searchResponse.data.files[0].id!;
  }

  return createFolder(name, parentId);
}
